const adjectives: string[] = [
    'adamant',
    'adroit',
    'amatory',
    'animistic',
    'antic',
    'arcadian',
    'baleful',
    'bellicose',
    'bilious',
    'boorish',
    'calamitous',
    'caustic',
    'cerulean',
    'comely',
    'concomitant',
    'contumacious',
    'corpulent',
    'crapulous',
    'defamatory',
    'didactic',
    'dilatory',
    'dowdy',
    'efficacious',
    'effulgent',
    'egregious',
    'endemic',
    'equanimous',
    'execrable',
    'fastidious',
    'feckless',
    'fecund',
    'friable',
    'fulsome',
    'garrulous',
    'guileless',
    'gustatory',
    'heuristic',
    'histrionic',
    'hubristic',
    'incendiary',
    'insidious',
    'insolent',
    'intransigent',
    'inveterate',
    'invidious',
    'irksome',
    'jejune',
    'jocular',
    'judicious',
    'lachrymose',
    'limpid',
    'loquacious',
    'luminous',
    'mannered',
    'mendacious',
    'meretricious',
    'minatory',
    'mordant',
    'munificent',
    'nefarious',
    'noxious',
    'obtuse',
    'parsimonious',
    'pendulous',
    'pernicious',
    'pervasive',
    'petulant',
    'platitudinous',
    'precipitate',
    'propitious',
    'puckish',
    'querulous',
    'quiescent',
    'rebarbative',
    'recalcitant',
    'redolent',
    'rhadamanthine',
    'risible',
    'ruminative',
    'sagacious',
    'salubrious',
    'sartorial',
    'sclerotic',
    'serpentine',
    'spasmodic',
    'strident',
    'taciturn',
    'tenacious',
    'tremulous',
    'trenchant',
    'turbulent',
    'turgid',
    'ubiquitous',
    'uxorious',
    'verdant',
    'voluble',
    'voracious',
    'wheedling',
    'withering',
    'zealous',
];
const nouns: string[] = [
    'ninja',
    'chair',
    'pancake',
    'statue',
    'unicorn',
    'rainbows',
    'laser',
    'senor',
    'bunny',
    'captain',
    'nibblets',
    'cupcake',
    'carrot',
    'gnomes',
    'glitter',
    'potato',
    'salad',
    'toejam',
    'curtains',
    'beets',
    'toilet',
    'exorcism',
    'stick figures',
    'mermaid eggs',
    'sea barnacles',
    'dragons',
    'jellybeans',
    'snakes',
    'dolls',
    'bushes',
    'cookies',
    'apples',
    'ice cream',
    'ukulele',
    'kazoo',
    'banjo',
    'opera singer',
    'circus',
    'trampoline',
    'carousel',
    'carnival',
    'locomotive',
    'hot air balloon',
    'praying mantis',
    'animator',
    'artisan',
    'artist',
    'colorist',
    'inker',
    'coppersmith',
    'director',
    'designer',
    'flatter',
    'stylist',
    'leadman',
    'limner',
    'make-up artist',
    'model',
    'musician',
    'penciller',
    'producer',
    'scenographer',
    'set decorator',
    'silversmith',
    'teacher',
    'auto mechanic',
    'beader',
    'bobbin boy',
    'clerk of the chapel',
    'filling station attendant',
    'foreman',
    'maintenance engineering',
    'mechanic',
    'miller',
    'moldmaker',
    'panel beater',
    'patternmaker',
    'plant operator',
    'plumber',
    'sawfiler',
    'shop foreman',
    'soaper',
    'stationary engineer',
    'wheelwright',
    'woodworkers',
];

const randomElement = (list: string[]) => {
    const i = Math.floor(Math.random() * list.length);
    return list[i];
};

export const randomName = (): string => `${randomElement(adjectives)} ${randomElement(nouns)}`;

export const snakeCase = (str: string) => {
    return str
        .replace(/\W+/g, ' ')
        .split(/ |\B(?=[A-Z])/)
        .map((word) => word.toLowerCase())
        .join('_');
};

export const UUID = (): string => {
    let result, i, j;
    result = '';
    for (j = 0; j < 32; j++) {
        if (j == 8 || j == 12 || j == 16 || j == 20) result = result + '-';
        i = Math.floor(Math.random() * 16)
            .toString(16)
            .toUpperCase();
        result = result + i;
    }
    return result;
};

export const toTitleCase = (toTransform: string) => {
    return toTransform.replace(/\b([a-z])/g, function (_, initial) {
        return initial.toUpperCase();
    });
};
